# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .customer import Customer as Customer
from .product_list_params import ProductListParams as ProductListParams
from .customer_list_params import CustomerListParams as CustomerListParams
from .documents_info_param import DocumentsInfoParam as DocumentsInfoParam
from .employee_list_params import EmployeeListParams as EmployeeListParams
from .product_list_response import ProductListResponse as ProductListResponse
from .voucher_create_params import VoucherCreateParams as VoucherCreateParams
from .customer_create_params import CustomerCreateParams as CustomerCreateParams
from .customer_list_response import CustomerListResponse as CustomerListResponse
from .customer_update_params import CustomerUpdateParams as CustomerUpdateParams
from .employee_list_response import EmployeeListResponse as EmployeeListResponse
from .supplier_create_params import SupplierCreateParams as SupplierCreateParams
from .supplier_update_params import SupplierUpdateParams as SupplierUpdateParams
from .voucher_create_response import VoucherCreateResponse as VoucherCreateResponse
from .attendance_create_params import AttendanceCreateParams as AttendanceCreateParams
from .attendance_delete_params import AttendanceDeleteParams as AttendanceDeleteParams
from .customer_create_response import CustomerCreateResponse as CustomerCreateResponse
from .customer_update_response import CustomerUpdateResponse as CustomerUpdateResponse
from .supplier_create_response import SupplierCreateResponse as SupplierCreateResponse
from .supplier_update_response import SupplierUpdateResponse as SupplierUpdateResponse
from .currency_get_rates_params import CurrencyGetRatesParams as CurrencyGetRatesParams
from .attendance_create_response import AttendanceCreateResponse as AttendanceCreateResponse
from .attendance_delete_response import AttendanceDeleteResponse as AttendanceDeleteResponse
from .currency_get_rates_response import CurrencyGetRatesResponse as CurrencyGetRatesResponse
from .purchase_quotation_list_params import PurchaseQuotationListParams as PurchaseQuotationListParams
from .category_retrieve_tree_response import CategoryRetrieveTreeResponse as CategoryRetrieveTreeResponse
from .product_retrieve_details_params import ProductRetrieveDetailsParams as ProductRetrieveDetailsParams
from .purchase_quotation_create_params import PurchaseQuotationCreateParams as PurchaseQuotationCreateParams
from .purchase_quotation_list_response import PurchaseQuotationListResponse as PurchaseQuotationListResponse
from .purchase_quotation_update_params import PurchaseQuotationUpdateParams as PurchaseQuotationUpdateParams
from .product_retrieve_details_response import ProductRetrieveDetailsResponse as ProductRetrieveDetailsResponse
from .sales_invoice_print_html_response import SalesInvoicePrintHTMLResponse as SalesInvoicePrintHTMLResponse
from .purchase_quotation_create_response import PurchaseQuotationCreateResponse as PurchaseQuotationCreateResponse
from .purchase_quotation_update_response import PurchaseQuotationUpdateResponse as PurchaseQuotationUpdateResponse
from .purchase_requisition_create_params import PurchaseRequisitionCreateParams as PurchaseRequisitionCreateParams
from .purchase_requisition_create_response import PurchaseRequisitionCreateResponse as PurchaseRequisitionCreateResponse
from .product_retrieve_created_after_params import (
    ProductRetrieveCreatedAfterParams as ProductRetrieveCreatedAfterParams,
)
from .product_retrieve_promoted_after_params import (
    ProductRetrievePromotedAfterParams as ProductRetrievePromotedAfterParams,
)
from .product_retrieve_created_after_response import (
    ProductRetrieveCreatedAfterResponse as ProductRetrieveCreatedAfterResponse,
)
from .product_retrieve_promoted_after_response import (
    ProductRetrievePromotedAfterResponse as ProductRetrievePromotedAfterResponse,
)
from .purchase_requisition_add_document_params import (
    PurchaseRequisitionAddDocumentParams as PurchaseRequisitionAddDocumentParams,
)
from .product_retrieve_updated_prices_after_params import (
    ProductRetrieveUpdatedPricesAfterParams as ProductRetrieveUpdatedPricesAfterParams,
)
from .product_retrieve_updated_prices_after_response import (
    ProductRetrieveUpdatedPricesAfterResponse as ProductRetrieveUpdatedPricesAfterResponse,
)
from .product_retrieve_updated_availability_after_params import (
    ProductRetrieveUpdatedAvailabilityAfterParams as ProductRetrieveUpdatedAvailabilityAfterParams,
)
from .product_retrieve_updated_availability_after_response import (
    ProductRetrieveUpdatedAvailabilityAfterResponse as ProductRetrieveUpdatedAvailabilityAfterResponse,
)
